version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - postgresql
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/pn_app_db
      - POSTGRES_DATABASE_URL=postgres://user:password@postgresql:5432/pn_app_db

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=pn_app_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql

  postgresql:
    image: postgres:13
    environment:
      - POSTGRES_DB=pn_app_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  mysql_data:
  postgres_data:
