# Generated by Django 3.0.7 on 2022-06-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0004_auto_20220313_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='power_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies', to='api_blog.Types'),
        ),
    ]
