# Generated by Django 4.2.1 on 2023-05-14 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaproductosCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url_clean', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'listaproductos_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaproductosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url_clean', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'listaproductos_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaproductosTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url_clean', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'listaproductos_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaComputadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('retroiluminado', models.IntegerField()),
                ('color', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=250)),
                ('lectordehuella', models.IntegerField(db_column='lectorDeHuella')),
                ('duracionbateria', models.IntegerField(db_column='duracionBateria')),
                ('fechaactualizacion', models.DateTimeField(db_column='fechaActualizacion')),
            ],
            options={
                'db_table': 'tienda_computadora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaDisco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('tipo', models.CharField(max_length=250)),
                ('velocidad', models.FloatField()),
                ('fechaactualizacion', models.DateTimeField(db_column='fechaActualizacion')),
            ],
            options={
                'db_table': 'tienda_disco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaMarca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('fechaactualizacion', models.DateTimeField(db_column='fechaActualizacion')),
            ],
            options={
                'db_table': 'tienda_marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaMarcaprocesador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fechaactualizacion', models.DateTimeField(db_column='fechaActualizacion')),
            ],
            options={
                'db_table': 'tienda_marcaprocesador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaProcesador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('velocidad', models.FloatField()),
                ('generacion', models.IntegerField()),
                ('fechaactualizacion', models.DateTimeField(db_column='fechaActualizacion')),
            ],
            options={
                'db_table': 'tienda_procesador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiendaRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('velocidad', models.FloatField()),
                ('fechaactualizacion', models.DateTimeField(db_column='fechaActualizacion')),
            ],
            options={
                'db_table': 'tienda_ram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(max_length=1000)),
                ('imagen', models.ImageField(upload_to='')),
                ('autor', models.CharField(max_length=50)),
                ('referencias', models.TextField(max_length=500)),
                ('fechaPublicacion', models.DateTimeField(default=datetime.datetime(2023, 5, 14, 0, 21, 54, 980818))),
                ('fechaActualizacion', models.DateTimeField()),
            ],
        ),
    ]
