# Generated by Django 4.2.1 on 2023-05-14 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnologias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fechaPublicacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 0, 28, 11, 569943)),
        ),
    ]
